#!/usr/bin/env python3
"""Compat wrapper for the packaged feed2toot-resigter-app entry point."""

import sys

from feed2toot.register_app import main


if __name__ == "__main__":
    sys.exit(main())
